[build]
  base    = "frontend"
  command = "flutter/bin/flutter build web --release --base-href /"
  publish = "frontend/build/web"

[build.environment]
  FLUTTER_VERSION = "3.27.0"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
